version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=travels
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    container_name: travel-service-api
    build:
      context: ./
      dockerfile: ./Dockerfile
    # depends_on:
    #   - db
    ports:
      - 8080:8080
    # environment:
      # MYSQL_HOST: db
      # MYSQL_PORT: 3306
      # MYSQL_DATABASE: travels
      # MYSQL_USER: root
      # MYSQL_PASSWORD: 123
    volumes:
      - ./:/src
volumes:
  db:
    driver: local
  


# docker images
# docker ps -a

# docker run -it -p 8080:80 nginx

# docker-compose up -d --build

# docker build -t travel-service-api:latest .
# docker run -d -p 8080:8080 --name travel-service-api travel-service-api:latest